# Generated by Django 4.2.1 on 2023-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("fname", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=1000)),
            ],
        ),
    ]
